### ISSUE TITLE
How about keeping a changelog?

### ISSUE THREAD

**Issue by ivan-kolmychek** [mz026/hash_police#1]
For instance, look at http://keepachangelog.com/ with its arguments and format

> - What’s the point of a change log?
> 
> To make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project.
> - Why can’t people just use a git log diff?
> 
> Because log diffs are full of noise — by nature. They could not make a suitable change log even in a hypothetical project run by perfect humans who never make typos, never forget to commit new files, never miss any part of a refactoring. The purpose of a commit is to document one atomic step in the process by which the code evolves from one state to another. The purpose of a change log is to document the noteworthy differences between these states.
> 
> As is the difference between good comments and the code itself, so is the difference between a change log and the commit log: one describes the why, the other the how.

**Comment by mz026** [comment]
just added CHANGELOG in this commit 51ad519 

thanks for your suggestion! @ivan-kolmychek

**Comment by ivan-kolmychek** [comment]
Thanks.
